include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI Support for Custom DMZ
LUCI_PKGARCH:=all

PKG_NAME:=luci-app-dmz-h1
PKG_VERSION:=1.0
PKG_RELEASE:=1

include $(TOPDIR)/feeds/luci/luci.mk

PKGARCH:=all

$(eval $(call BuildPackage,luci-app-dmz-h1))
